version: '3.8'

services:
  server:
    build: .
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/app
    command: air cmd/app.go -b 0.0.0.0
  redis:
    image: redis:alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
     - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local